"""Bot knowledge retrieval for Telegram planning and answers."""

from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List

BASE_CONTEXT = """
Apex is a crypto trading bot. The execution engine, not the LLM, decides trades.
The recommended brain is drl_event_fusion: DRL and deterministic technical logic decide entries while cached event and macro scores adjust conviction.
Ollama is used as a parser and explainer. Gemini is used as a slower macro and reporting layer.
Synthetic exits are safety rails. ATR and strategy stop logic prevent catastrophic loss, while min_hold_min and max_hold_min keep long-hold strategies from being treated like scalps.
brain_mode and opening_strategy are different fields. brain_mode explains how a decision was formed. opening_strategy explains how the position should be managed.
""".strip()

DATASET_CONTEXT: Dict[str, str] = {
    "account_summary": "account_summary is the current account state: equity, cash, buying power, and high-level balance information.",
    "current_positions": "current_positions contains live open positions, quantities, average entry, current price, and unrealized PnL.",
    "actions": "actions is the operational audit trail: orders submitted, close requests, blocks, and bot actions with reasons.",
    "live_experience": "live_experience stores trade memory. Each row captures entry context, strategy_used, side, entry price, event and macro scores at entry, and later the exit outcome when the trade closes.",
    "news_events": "news_events stores persisted parsed headlines from CryptoPanic, Binance, and related feeds. Each event has source, event_type, sentiment, impact_score, confidence, and TTL.",
    "decision_traces": "decision_traces stores why the brain submitted or blocked a trade, including final_score, submitted flag, block_reason, and strategy metadata.",
    "event_state": "event_state is the cached per-symbol event summary used by the bot. It aggregates active news into net_event_score, event_bias, hard_veto, golden_trade_flag, and top_event_type.",
    "macro_consensus": "macro_consensus is the latest Gemini-style regime snapshot, including risk_multiplier, market_regime, and a short macro summary.",
    "reports": "reports are hourly or daily narrative summaries generated by the bot from local account, score, and news state.",
    "live_news": "live_news is fresh on-demand news pulled at query time from CryptoPanic or Binance support announcements. It is not necessarily persisted yet.",
    "current_indicators": "current_indicators is a live technical indicator snapshot built from recent bars. It includes RSI, EMA trend, Bollinger bands, and recent close context for a specific symbol.",
    "tracked_symbols": "tracked_symbols contains the bot-managed tracked-coin state: active, recently_active, saved, active_reason, monitor_tier, and timestamps.",
    "decision_outcomes": "decision_outcomes stores forward feedback for a decision at 30m, 1h, 6h, and 24h horizons, including good_entry, bad_entry, good_block, and bad_block labels.",
    "symbol_policy_overlay": "symbol_policy_overlay stores per-symbol learning adjustments such as score_delta, size_multiplier, confidence_boost, and decision_samples.",
    "brain_self_score": "brain_self_score is the bot's latest global self-evaluation snapshot, including score and confidence over recent outcomes and overlays.",
    "oracle_state": "oracle_state is the current Gemini macro oracle cache, including breadth_state, drivers, mentioned_symbols, summary_source, and provider status.",
}

STRATEGY_CONTEXT: Dict[str, str] = {
    "micro_scalper": "micro_scalper is a short-hold strategy with tight profit targets and tight stop logic.",
    "mean_reversion": "mean_reversion buys weakness into oversold conditions and expects a bounce, usually on a shorter hold than swing trades.",
    "breakout_momentum": "breakout_momentum buys strength after confirmation and volume expansion, but it is still managed with tighter holds than swing or position trades.",
    "dynamic_dca": "dynamic_dca scales into dips gradually and is expected to hold longer than scalp strategies.",
    "ai_macro": "ai_macro is a broader, slower strategy guided by macro context rather than a quick tactical flip.",
    "dual_brain": "dual_brain is the legacy mode where DRL and Ollama both influenced decisions.",
    "drl": "drl is the fast non-LLM execution mode where DRL and deterministic logic decide entries directly.",
    "drl_event_fusion": "drl_event_fusion is the current recommended mode. DRL and technical logic drive the decision while event_state and macro_consensus adjust conviction, sizing, or vetoes.",
    "swing_momentum": "swing_momentum is a multi-hour to multi-day strategy. It should not be treated like a scalp and normally has a larger min_hold_min and max_hold_min.",
    "position_golden_cross": "position_golden_cross is a long-hold strategy built to hold for days or weeks with wider stop and longer hold windows.",
}

SCORE_CONTEXT: Dict[str, str] = {
    "net_event_score": "net_event_score is the aggregate bullish or bearish weight of active news events for one symbol.",
    "event_bias": "event_bias is the direction of the cached event signal: bullish, bearish, or neutral.",
    "hard_veto": "hard_veto means the event layer is strong enough to block new buys even if technicals look good.",
    "golden_trade_flag": "golden_trade_flag marks an unusually strong positive catalyst, such as a high-confidence listing event.",
    "risk_multiplier": "risk_multiplier is the macro regime multiplier. Below 1.0 means caution or bear conditions. Above 1.0 means more supportive conditions.",
    "final_score": "final_score is the fused conviction score used in decision traces after technical, event, macro, and penalty components are combined.",
    "event_score_at_entry": "event_score_at_entry is the cached event contribution present when the trade was opened.",
    "pressure_score": "pressure_score is the activity governor's quiet-versus-overactive score. Negative means too quiet, positive means too hot.",
    "effectiveness_score": "effectiveness_score measures whether the current governor mode has been helping or hurting recently.",
}

EXIT_CONTEXT = """
Exit behavior is strategy-aware. The bot can take partial profits, trail winners, and stop losers.
min_hold_min prevents a healthy swing or position trade from being exited too quickly unless risk controls demand it.
max_hold_min defines the longest intended hold window for that strategy.
Synthetic exits and ATR-based risk logic are safeguards, not a strategy replacement.
""".strip()

_DOC_ROOT = Path(__file__).resolve().parents[2] / "docs"
_KNOWLEDGE_ROOT = _DOC_ROOT / "bot_knowledge"
_DOCS: List[Dict[str, Any]] = [
    {
        "name": "crypto_readme",
        "path": Path(__file__).resolve().parents[2] / "services" / "crypto" / "README.md",
        "keywords": {"strategy", "exit", "atr", "synthetic", "hold", "tp", "stop", "safeguard", "risk"},
        "priority": 1.0,
    },
    {
        "name": "telegram_bot_context",
        "path": _DOC_ROOT / "telegram_bot_context.md",
        "keywords": {"telegram", "query", "event_state", "live_experience", "macro", "brain_mode"},
        "priority": 1.2,
    },
    {
        "name": "drl_event_fusion_plan",
        "path": _DOC_ROOT / "drl_event_fusion_implementation_plan.md",
        "keywords": {"drl", "fusion", "macro", "news", "event", "decision", "trace", "schema"},
        "priority": 0.9,
    },
    {
        "name": "bot_data_dictionary",
        "path": _KNOWLEDGE_ROOT / "bot_data_dictionary.md",
        "keywords": {"dataset", "schema", "event_state", "live_experience", "decision_trace", "risk_state", "governor"},
        "priority": 1.5,
    },
    {
        "name": "strategy_glossary",
        "path": _KNOWLEDGE_ROOT / "strategy_glossary.md",
        "keywords": {"strategy", "hold", "opening_strategy", "swing", "scalper", "dca"},
        "priority": 1.4,
    },
    {
        "name": "risk_state_reference",
        "path": _KNOWLEDGE_ROOT / "risk_state_reference.md",
        "keywords": {"risk_state", "halted", "restricted", "cautious", "resume", "oracle", "drawdown"},
        "priority": 1.4,
    },
    {
        "name": "telegram_query_intents",
        "path": _KNOWLEDGE_ROOT / "telegram_query_intents.md",
        "keywords": {"intent", "query", "rsi", "ema", "trade_history", "indicator", "news", "debug"},
        "priority": 1.6,
    },
]
_STOPWORDS = {
    "the", "and", "for", "with", "this", "that", "from", "what", "why", "when", "how", "show", "last", "today", "yesterday",
    "current", "latest", "tell", "about", "status", "report", "reports", "question", "answer", "bot", "symbol", "trade", "trades",
}


def _dedupe_preserve_order(values: Iterable[str]) -> List[str]:
    seen = set()
    ordered: List[str] = []
    for value in values:
        key = str(value or "").strip().lower()
        if not key or key in seen:
            continue
        seen.add(key)
        ordered.append(str(value).strip())
    return ordered


def _extract_relevant_strategies(evidence: Dict[str, Any]) -> List[str]:
    values: List[str] = []
    for row in evidence.get("live_experience") or []:
        strategy = str(row.get("strategy_used") or row.get("opening_strategy") or "").strip()
        if strategy:
            values.append(strategy)
    plan = evidence.get("plan") or {}
    brain_mode = str(plan.get("brain_mode") or "").strip()
    if brain_mode:
        values.append(brain_mode)
    return _dedupe_preserve_order(values)


@lru_cache(maxsize=64)
def _read_doc(path_str: str) -> str:
    path = Path(path_str)
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def _tokenize(text: str) -> List[str]:
    return [token for token in re.findall(r"[a-zA-Z_]{2,}", str(text or "").lower()) if token not in _STOPWORDS]


def _query_terms(question: str, plan: Dict[str, Any] | None = None, evidence: Dict[str, Any] | None = None) -> set[str]:
    terms = set(_tokenize(question))
    plan = plan or {}
    evidence = evidence or {}
    intent = str(plan.get("intent") or "")
    if intent:
        terms.add(intent)
    for dataset in plan.get("datasets", []) or []:
        terms.add(str(dataset).lower())
    symbol = str(plan.get("symbol") or "")
    if symbol:
        terms.add(symbol.split("/")[0].lower())
    for strategy in _extract_relevant_strategies(evidence):
        terms.add(strategy.lower())
    event_state = evidence.get("event_state") or {}
    for key in ("event_bias", "top_event_type"):
        value = str(event_state.get(key) or "").strip().lower()
        if value:
            terms.add(value)
    return terms


def retrieve_knowledge(question: str, plan: Dict[str, Any] | None = None, evidence: Dict[str, Any] | None = None, *, max_docs: int = 4) -> List[Dict[str, str]]:
    terms = _query_terms(question, plan, evidence)
    term_text = " ".join(sorted(terms))
    scored: List[tuple[float, Dict[str, Any], str]] = []
    for entry in _DOCS:
        content = _read_doc(str(entry["path"]))
        if not content:
            continue
        lowered = content.lower()
        score = float(entry.get("priority", 1.0))
        keyword_hits = 0
        for keyword in entry.get("keywords", set()):
            lowered_keyword = str(keyword).lower()
            if lowered_keyword in terms:
                keyword_hits += 1
                score += 2.5
            elif lowered_keyword in lowered and lowered_keyword in term_text:
                score += 0.5
        for term in terms:
            if term and term in lowered:
                score += 0.15
        if keyword_hits == 0 and entry["name"] in {"bot_data_dictionary", "telegram_query_intents"}:
            score += 1.0
        scored.append((score, entry, content))

    scored.sort(key=lambda item: item[0], reverse=True)
    selected: List[Dict[str, str]] = []
    for _score, entry, content in scored[: max(1, max_docs)]:
        excerpt = content.strip()
        if len(excerpt) > 2200:
            excerpt = excerpt[:2200].rsplit("\n", 1)[0]
        selected.append({
            "name": str(entry["name"]),
            "path": str(entry["path"]),
            "content": excerpt,
        })
    return selected


def planner_context(question: str = "") -> str:
    docs = retrieve_knowledge(question, {"intent": "planner"}, {}, max_docs=3)
    dataset_lines = [DATASET_CONTEXT[key] for key in sorted(DATASET_CONTEXT)]
    doc_sections = [f"[{doc['name']}]\n{doc['content']}" for doc in docs]
    return "\n\n".join([
        BASE_CONTEXT,
        "Dataset meanings:\n" + "\n".join(dataset_lines),
        *doc_sections,
        EXIT_CONTEXT,
    ]).strip()


def answer_context(question: str, plan: Dict[str, Any], evidence: Dict[str, Any]) -> str:
    sections: List[str] = [BASE_CONTEXT]
    datasets = [str(item) for item in plan.get("datasets", []) if str(item) in DATASET_CONTEXT]
    if datasets:
        sections.append("Relevant data definitions:")
        sections.extend(f"- {DATASET_CONTEXT[item]}" for item in datasets)

    strategy_lines = []
    for strategy in _extract_relevant_strategies(evidence):
        if strategy in STRATEGY_CONTEXT:
            strategy_lines.append(f"- {STRATEGY_CONTEXT[strategy]}")
    if strategy_lines:
        sections.append("Relevant strategy context:")
        sections.extend(strategy_lines)

    if any(item in datasets for item in ("event_state", "news_events", "live_news", "decision_traces", "current_indicators")):
        sections.append("Relevant score meanings:")
        sections.extend(f"- {value}" for value in SCORE_CONTEXT.values())

    docs = retrieve_knowledge(question, plan, evidence, max_docs=4)
    if docs:
        sections.append("Retrieved bot knowledge:")
        for doc in docs:
            sections.append(f"[{doc['name']}]\n{doc['content']}")

    sections.append(EXIT_CONTEXT)
    return "\n\n".join(section for section in sections if section).strip()


__all__ = [
    "BASE_CONTEXT",
    "DATASET_CONTEXT",
    "STRATEGY_CONTEXT",
    "SCORE_CONTEXT",
    "EXIT_CONTEXT",
    "planner_context",
    "answer_context",
    "retrieve_knowledge",
]
